
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskDB?createDatabaseIfNotExist=true
    username: root
    password: sql_18183528
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  application:
    name: task