server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ravikugan/spring-cloud-config-store
          search-paths:
          - '*service'
          #incase private we can give username and password here
          default-label: main